### ISSUE TITLE
Willing to take contributors ?

### ISSUE THREAD

**Issue by DevHyperCoder** [venkatarun95/rust-book-hindi#1]
Hey bro!

Really nice so far ; i would like to contribute for this translation (might help someone) ; may i know the details on how ur doing it ?

mainly the hindi typing part

PS: Great

**Comment by venkatarun95** [comment]
Yes, contributions are very welcome! Thanks!

Initially I wrote a little atom plugin to type hindi: https://github.com/venkatarun95/atom-devanagari

There are lots of more mature tools available for doing that as well. These days, I just use the Hindi Bolnagri keyboard in Ubuntu
